blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostListView.as_view(), name='posts'),
    path('<slug:slug>-<int:pk>', views.PostDetailView.as_view(), name='post'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
import markdown
from django.conf import settings
from django.db import models


class Post(models.Model):
    """A blog post that is auto-created from Markdown input"""
    title = models.CharField(max_length=200, blank=True)
    author = models.ForeignKey(to=settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    slug = models.SlugField()
    posted_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    body = models.TextField()
    body_rendered = models.TextField(blank=True)

    def save(self, *args, **kwargs):
        self.body_rendered = markdown.markdown(
            self.body, extensions=['codehilite', 'fenced_code'])
        super().save(*args, **kwargs)

    def __str__(self):
        """Use the title as the representation"""
        return self.title

    class Meta:
        ordering = ('-posted_date', )

blog/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView

from .models import Post


class PostListView(ListView):
    model = Post


class PostDetailView(DetailView):
    model = Post

blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block cover %}
  <img class="cover" src="https://images.squarespace-cdn.com/content/v1/5330c121e4b0ec02b60123b4/1595276169995-O3Z0C64FM64CGTTBT775/ke17ZwdGBToddI8pDm48kMXRibDYMhUiookWqwUxEZ97gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z4YTzHvnKhyp6Da-NYroOW3ZGjoBKy3azqku80C789l0luUmcNM2NMBIHLdYyXL-Jww_XBra4mrrAHD6FMA3bNKOBm5vyMDUBjVQdcIrt03OQ/0V5A1630.JPG?format=500w">
{% endblock cover %}

{% block content %}
<section class="article-body">
  <span class="article-info"><a class="author" href="">{{ post.author }}</a> on <em>{{ post.posted_date | date:"F jS" }}</em></span>
  {{ post.body_rendered | safe }}
</section>
{% endblock content %}

blog/templates/blog/post_list.html
{% extends "base.html" %}

{% block content %}
<section id="articles">
  {% for post in post_list %}
  <a href="{% url 'blog:post' slug=post.slug pk=post.pk %}" class="article">
    <img class="cover" src="https://images.squarespace-cdn.com/content/v1/5330c121e4b0ec02b60123b4/1595276169995-O3Z0C64FM64CGTTBT775/ke17ZwdGBToddI8pDm48kMXRibDYMhUiookWqwUxEZ97gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z4YTzHvnKhyp6Da-NYroOW3ZGjoBKy3azqku80C789l0luUmcNM2NMBIHLdYyXL-Jww_XBra4mrrAHD6FMA3bNKOBm5vyMDUBjVQdcIrt03OQ/0V5A1630.JPG?format=500w">
    <h2 class="title">{{ post.title }}</h2>
    <p class="date">{{ post.posted_date | date:'M j' }}</p>
  </a>
  {% endfor %}
</section>
{% endblock content %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Fonts -->
    <link rel="stylesheet" href="https://use.typekit.net/qrf6xbk.css">

    <!-- Styles -->
    <link rel="stylesheet" href="{% static 'normalize.css' %}">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link rel="stylesheet" href="{% static 'menu.css' %}">
    <link rel="stylesheet" href="{% static 'codehilite.css' %}">

    <title>Adventure Log</title>
  </head>
  <body>
    <div class="content">
      <header>
        <div id="title">
          <h6>Jack Sol</h6>
          <h1><a href="{% url 'blog:posts' %}">Adventure Log</a></h1>
        </div>

        {% block cover %}{% endblock %}

        <nav role="navigation" id="menu">
          <input type="checkbox" id="toggle">
          <span id="menu-icon">
            <span></span>
            <span></span>
            <span></span>
          </span>
          <ul id="menu-list">
            <li><a href="{% url 'blog:posts' %}">Home</a></li>
            <li><a href="">Adventures</a></li>
            <li><a href="">Projects</a></li>
          </ul>
        </nav>

        <nav role="navigation" id="profile">
          <input type="checkbox" id="toggle">
          <span id="profile-icon">
            <span class="head"></span>
            <span class="body"></span>
          </span>
          <ul id="profile-list">
            <li><a href="">Portfolio</a></li>
            <li><a href="https://www.instagram.com/jvcksol/">Instagram</a></li>
            <li><a href="https://www.youtube.com/jackn/">YouTube</a></li>
          </ul>
        </nav>

      </header>
      {% block content %}
      {% endblock content %}
    </div>

    <footer>
      <div class="content">
        <h1 class="title">Jack Sol</h1>
      </div>

      <div class="content">
        <h2><a href="">About</a></h2>
        <h2><a href="">Work</a></h2>
        <h2><a href="">Contact</a></h2>
        <h2><a href="">Github</a></h2>
      </div>

      <div class="content">
        <h2><a href="">Terms of Service</a></h2>
        <h2><a href="">Privacy Policy</a></h2>
        <h2><a href="">Legal</a></h2>
      </div>
    </footer>

  </body>
</html>